story7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
]

web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index, name='index'),
    path('story7/', views.javascript, name='javascript'),
    path('caribuku/', views.cari, name='cari'),
    path('login/', views.logIn, name='logIn'),
    path('signIn/', views.signIn, name='signIn'),
    path('logout/', views.logOut, name='logOut'),
]

web/models.py
from django.db import models
from django.contrib.auth.models import User

class Akun(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

web/forms.py
from django import forms
from .models import Akun
from django.contrib.auth import get_user_model

User = get_user_model()

class Login(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class SignIn(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password_check = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

web/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib import messages
import requests
from .forms import SignIn, Login
import json

User = get_user_model()

def index(request):
    return render(request, 'index.html')

def javascript(request):
    return render(request, 'javascript.html')

def cari(request):
    response = {}
    return render(request, 'ajax.html', response)

def ajax(request):
    arg = request.GET['q']
    url = 'https://www.googleapis.com/books/v1/volumes?q=' + arg
    q = requests.get(url)
    data = json.loads(q.content)
    return JsonResponse(data, safe=False)

def logIn(request):
    form = Login(request.POST or None)
    response = {
        'form' : form,
        'akun' : False,
    }
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            response = {
                'form' : form,
                'akun' : True,
            }
            return render(request, "login.html", response)
    return render(request, "login.html", response)

def signIn(request):
    form = SignIn(request.POST or None)
    response = {
        'form' : form,
        'uname' : False,
        'sandi' : False,
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        password_check = form.cleaned_data.get("password_check")
        try:
            if password != password_check:
                response = {
                    'form' : form,
                    'uname' : False,
                    'sandi' : True,
                }
                return render(request, "signin.html", response)
            else:
                User.objects.create_user(username, email, password)
                user = authenticate(username=username, password=password)
                login(request, user)
                return redirect('/')
        except:
            if password != password_check:
                response = {
                    'form' : form,
                    'uname' : True,
                    'sandi' : True,
                }
                return render(request, "signin.html", response)
            else:
                response = {
                    'form' : form,
                    'uname' : True,
                    'sandi' : False,
                }
                return render(request, "signin.html", response)
    return render(request, "signin.html", response)

def logOut(request):
    logout(request)
    return render(request, 'logout.html')

web/templates/ajax.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    {% include "navbar.html" %}

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'ajax.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <title>Homepage</title>
    </head>
    
    <body>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-10">
                    <input id="input" placeholder="Type to search...">
                </div>
            </div> 
        </div>

        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <h3 id="tampilan"></h3>
                </div>
            </div>
        </div>

        <script type="text/javascript">
            $("#input").keyup(function() {
                var isian = $("#input").val();
                var url_isian = 'https://www.googleapis.com/books/v1/volumes?q=' + isian;
                $.ajax ({
                    url : url_isian,
                    success : function(tampilan) {
                        console.log(tampilan.items);
                        var objek_hasil = $("#tampilan");
                        objek_hasil.empty();

                        for (i=0; i<tampilan.items.length; i++) {
                            var tmp_title = tampilan.items[i].volumeInfo.title;
                            var tmp_thumbnails = tampilan.items[i].volumeInfo.imageLinks.smallThumbnail;
                            var tmp_link = tampilan.items[i].volumeInfo.canonicalVolumeLink;
                            console.log(tmp_title);
                            objek_hasil.append('<a href=' + tmp_link + ' target="_blank" style="text-decoration: none; color: #A6DCEF;">' + tmp_title + '</a> <br> <img src=' + tmp_thumbnails + ' style="width: 180px; height: 240px"> <br><br>');
                        }
                    }
                });
            });
        </script>
    </body>
    
</html>

web/templates/index.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    {% include "navbar.html" %}

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
        <title>Homepage</title>
    </head>
    
    <body>
        <div class="container awal">
            <div class="row justify-content-center">
                <div class="col-md-4 text-center">
                    <img class="self center-block" src="https://maung.id/static/3218f16a5414379bac2e0ca2bc5b348b/9f583/KR09.jpg" alt="Aryuda O.">
                    <br>
                    <a class="source" href="https://maung.id/aryuda.oktawyandra" target="_blank">Source</a>
                </div>
                <div class="col-md-8">
                    {% if user.is_authenticated %}
                        <h2 class="hello">Hello {{user.username}}</h2>
                    {% else %}
                        <h2 class="hello">Hello People</h2>
                    {% endif %}
                    <article class="welcome">My name is Yuda, and welcome to my web</article>
                    <article class="welcome">Please don’t leave your seat, and make sure to fasten your seat belt</article>
                    <article class="welcome">Enjoy your time :)</article>
                </div>                
            </div>      
        </div>

        <h1 class="edu">Education Background</h1>
        <br>

        <div class="container">
            <div class="row text-center justify-content-center">
                <div class="col-md-3 background">
                    <h3 class="class">Junior High School</h3>
                    <img class="classpic center-block" src="https://4.bp.blogspot.com/-o6pJdteu8C4/UOA_-7Q6PWI/AAAAAAAAJc8/9dj8WgFLCy0/s1600/LOGO+OSIS+SMP.png" alt="Logo SMP">
                    <h4 class="place">SMPN 91 Jakarta</h4>
                </div>
                <div class="col-md-3 offset-sm-1 background">
                    <h3 class="class">Senior High School</h3>
                    <img class="classpic center-block" src="https://1.bp.blogspot.com/-k1X-FZql9z4/UOA_sQfMy2I/AAAAAAAAJc0/OibdJLa5tAU/s1600/LOGO+OSIS+SMA.png" alt="Logo SMA">
                    <h4 class="place">SMAN 39 Jakarta</h4>
                </div>
                <div class="col-md-3 offset-sm-1 background">
                    <h3 class="class">College University</h3>
                    <img class="UIpic center-block" src="https://upload.wikimedia.org/wikipedia/id/thumb/9/95/Makara_UI.png/1200px-Makara_UI.png" alt="Logo UI">
                    <h4 class="place">University of Indonesia</h4>
                </div>
            </div>
        </div>

        <h1 class="contact">Contact Me</h1>
        <table class="excontact">
            <th>
                <td>
                    <a href="https://line.me/R/ti/p/aryuda145" target="_blank">
                        <img class="line" src="{% static 'Images/line.png' %}" alt="Line">
                    </a>
                    <a href="https://wa.me/+6281212945027" target="_blank">
                        <img class="whatsapp" src="{% static 'Images/whatsapp.png' %}" alt="Whatsapp">
                    </a>
                    <a href="https://id.linkedin.com/in/aryuda-oktawyandra-2703bb195" target="_blank">
                        <img class="linkedin" src="{% static 'Images/linkedin.png' %}" alt="LinkedIn">
                    </a>
                </td>
            </th>
        </table>
        <br>
        <br>
    </body>

</html>

web/templates/javascript.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    {% include "navbar.html" %}

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'javascript.css' %}">
        <title>Homepage</title>
    </head>
    
    <body>

        <div class="batas">
            <button class="pertanyaan">Apa bedanya fitnah sama fitness?</button>
            <div class="jawab">
                <p class="jawaban">Kalau fitnah, kejam. Kalau fitness, ke-gym</p>
            </div>
    
            <button class="pertanyaan">Pulau apa yang selalu santai?</button>
            <div class="jawab">
                <p class="jawaban">Pulau selowsi</p>
            </div>
    
            <button class="pertanyaan">Sapi, sapi apa yang bisa nempel di tembok?</button>
            <div class="jawab">
                <p class="jawaban">Stiker sapi</p>
            </div>
    
            <button class="pertanyaan">Hantu apa yang ngga pernah jujur?</button>
            <div class="jawab">
                <p class="jawaban">Sundel bohong</p>
            </div>
    
            <button class="pertanyaan">Kenapa ada hari guru, tapi ngga ada hari dosen?</button>
            <div class="jawab">
                <p class="jawaban">Karena doesn't</p>
            </div>
    
            <button class="pertanyaan">Siapa rapper yang sering batal puasa?</button>
            <div class="jawab">
                <p class="jawaban">Eminum</p>
            </div>
    
            <button class="pertanyaan">Huruf apa yang paling dingin?</button>
            <div class="jawab">
                <p class="jawaban">Huruf B, karena ada di tengah-tengah AC</p>
            </div>
        </div>

        <script>
        var acc = document.getElementsByClassName("pertanyaan");
        var i;
        for (i=0; i<acc.length; i++) {
            acc[i].addEventListener("click", function() {
                this.classList.toggle("active");
                var jawab = this.nextElementSibling;
                if (jawab.style.maxHeight) {
                    jawab.style.maxHeight = null;
                } else {
                    jawab.style.maxHeight = jawab.scrollHeight + "px";
                } 
            });
        }
        </script>

    </body>
</html>

web/templates/login.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    {% include "navbar.html" %}

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'akun.css' %}">
        <title>Homepage</title>
    </head>
    
    <body>
        <div class="container">

            <form action="{% url 'web:logIn' %}" method="POST">
                {% csrf_token %}
                <div class="row justify-content-center margin">
                    <div class="col-md-2">
                        <h4 class="judul">Username</h4>
                    </div>
                    <div class="col-md-10">
                        {% csrf_token %}
                        {{ form.username }}
                    </div>
                </div>

                <div class="row justify-content-center margin">
                    <div class="col-md-2">
                        <h4 class="judul">Password</h4>
                    </div>
                    <div class="col-md-10">
                        {% csrf_token %}
                        {{ form.password }}
                        {% if akun %}
                            <h5 class="error">
                                The account doesn't exist. Please try again or
                                <a href="{% url 'web:signIn' %}" class="switch">Sign In</a>
                            </h5>
                        {% endif %}
                    </div>       
                </div>

                <div class="row margin">
                    <div class="col-sm-3">
                        <input class="submit" type="submit" value="Submit">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-3 margin">
                        <a href="{% url 'web:signIn' %}" class="switch">
                            <h5>Don't have an account yet?</h5>
                        </a>
                    </div>   
                </div>
            </form>
        </div>

    </body>
</html>

web/templates/logout.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    {% include "navbar.html" %}

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'akun.css' %}">
        <title>Homepage</title>
    </head>
    
    <body>
        <div class="container">
            <div class="row justify-content-center  logout">
                <div class="col-md-12 text-center">
                    <h2 class="judul">You've logged out. Try again?</h2>
                </div>
            </div>
    
            <div class="row justify-content-center  logout">
                <div class="col-sm-2 m-2 text-center">
                    <a href="{% url 'web:logIn' %}">
                        <button class="submit" type="submit">Login</button>
                    </a>
                </div>
                <div class="col-sm-2 m-2 text-center">
                    <a href="{% url 'web:signIn' %}">
                        <button class="submit" type="submit">Sign In</button>
                    </a>
                </div>
                <div class="col-sm-2 m-2 text-center">
                    <a href="{% url 'web:index' %}">
                        <button class="submit" type="submit">Home</button>
                    </a>
                </div>
    
            </div>
        </div>
    </body>
</html>

web/templates/navbar.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'navbar.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <title>Story Aryuda</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark topnav">
      <a class="navbar-link" href="{% url 'web:index' %}">
        <h4 class="home hover">Home</h4>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link" href="{% url 'web:javascript' %}">
            <h4 class="hover">Story 7</h4>
          </a>
          <a class="nav-link" href="{% url 'web:cari' %}">
            <h4 class="hover">Cari Buku</h4>
          </a>
        </div>

        <div class="navbar-nav kanan">
          {% if user.is_authenticated %}
            <a class="nav-link" href="/">
              <h4 class="hover">{{user.username}}</h4>
            </a>
            <a class="nav-link" href="{% url 'web:logOut' %}">
              <h4 class="hover">Logout</h4>
            </a>
          {% else %}
            <div class="navbar-nav">
              <a class="nav-link" href="{% url 'web:logIn' %}">
                <h4 class="hover">Login</h4>
              </a>
              <a class="nav-link" href="{% url 'web:signIn' %}">
                <h4 class="hover">Sign In</h4>
              </a>
            </div>
          {% endif %}
        </div>
      </div>
    </nav>

  </body>
</html>

web/templates/signin.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    {% include "navbar.html" %}

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'akun.css' %}">
        <title>Homepage</title>
    </head>
    
    <body>
        <div class="container">

            <form action="{% url 'web:signIn' %}" method="POST">
                {% csrf_token %}
                <div class="row justify-content-center margin">
                    <div class="col-md-2">
                        <h4 class="judul">Username</h4>
                    </div>
                    <div class="col-md-10">
                        {% csrf_token %}
                        {{ form.username }}
                        {% if uname %}
                            <h5 class="error">The username you've chosen is unavailable. Find another one or
                                <a href="{% url 'web:logIn' %}" class="switch">Login</a>
                            </h5>
                        {% endif %}
                    </div>
                </div>

                <div class="row justify-content-center margin">
                    <div class="col-md-2">
                        <h4 class="judul">Email</h4>
                    </div>
                    <div class="col-md-10">
                        {% csrf_token %}
                        {{ form.email }}
                    </div>       
                </div>

                <div class="row justify-content-center margin">
                    <div class="col-md-2">
                        <h4 class="judul">Password</h4>
                    </div>
                    <div class="col-md-10">
                        {% csrf_token %}
                        {{ form.password }}
                    </div>       
                </div>

                <div class="row justify-content-center margin">
                    <div class="col-md-2">
                        <h4 class="judul">Confirm Pass</h4>
                    </div>
                    <div class="col-md-10">
                        {% csrf_token %}
                        {{ form.password_check }}
                        {% if sandi %}
                            <h5 class="error">The two password are not identical</h5>
                        {% endif %}
                    </div>       
                </div>

                <div class="row margin">
                    <div class="col-sm-3">
                        <input class="submit" type="submit" value="Submit">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-3 margin">
                        <a href="{% url 'web:logIn' %}" class="switch">
                            <h5>Have an account already?</h5>
                        </a>
                    </div>   
                </div>
            </form>
        </div>

    </body>
</html>